export default [
  {
      id: 1,
      title: "Samsung Galaxy S7",
      price: 700.0,
      img: "https://res.cloudinary.com/drecbsopp/image/upload/v1627398399/samasung-galaxy-a51-8gb-8uh_tndbgv.jpg",
      quantity: 1,
      internalMemory: "32GB",
      display: "5.1 inches",
      processor: "Qualcomm Snapdragon 820",
      rearCamera: "12 MP",
      frontCamera: "5 MP",
      battery: "3000 mAh",
      operatingSystem: "Android v6.0 (Marshmallow)",
      ram: "4GB"
  },
  {
      id: 2,
      title: "Moto G5 Plus",
      price: 600.0,
      img: "https://res.cloudinary.com/drecbsopp/image/upload/v1627398477/MotoGPowerDual_2021_Reformatted_1_330x_wp8gve.png",
      quantity: 1,
      internalMemory: "32GB",
      display: "5.2 inches",
      processor: "Qualcomm Snapdragon 625",
      rearCamera: "12 MP",
      frontCamera: "5 MP",
      battery: "3000 mAh",
      operatingSystem: "Android v7.0 (Nougat)",
      ram: "2GB"
  },
  {
      id: 3,
      title: "Xiaomi Redmi Note 2",
      price: 500.0,
      img: "https://res.cloudinary.com/drecbsopp/image/upload/v1627398543/D7A7DA95-AEF8-228B-A2D2-A3FEBF237C33_y9p6wq.png",
      quantity: 1,
      internalMemory: "16GB",
      display: "5.5 inches",
      processor: "Mediatek MT6795 Helio X10",
      rearCamera: "13 MP",
      frontCamera: "5 MP",
      battery: "3060 mAh",
      operatingSystem: "Android v5.0 (Lollipop)",
      ram: "2GB"
  },
  {
    id: 4,
    title: "Nokia G20",
    price: 400.0,
    img: "https://res.cloudinary.com/drecbsopp/image/upload/v1627398698/nokia3_resize_md_qdw7bv.jpg",
    quantity: 1,
    internalMemory: "32GB",
  display: "5.2 inches",
       processor: "Qualcomm Snapdragon 625",
      rearCamera: "12 MP",
      frontCamera: "5 MP",
      battery: "3000 mAh",
      operatingSystem: "Android v7.0 (Nougat)",
      ram: "2GB"
  },
  {
    id: 5,
    title: "Apple iPhone 13 Pro Max",
    price: 4000.0,
    img: "https://www.91-img.com/gallery_images_uploads/3/d/3df5ca6a9b470f715b085991144a5b76e70da975.JPG?tr=h-550,w-0,c-at_max",
    quantity: 1,
    internalMemory: "32GB",
      display: "5.1 inches",
      processor: "Qualcomm Snapdragon 820",
      rearCamera: "12 MP",
      frontCamera: "5 MP",
      battery: "3000 mAh",
      operatingSystem: "Android v6.0 (Marshmallow)",
      ram: "4GB"
  },
  {
    id: 6,
    title: "Google Pixel 6",
    price: 599.0,
    img: "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-6.jpg",
    quantity: 1,
    internalMemory: "16GB",
      display: "5.5 inches",
      processor: "Mediatek MT6795 Helio X10",
      rearCamera: "13 MP",
      frontCamera: "5 MP",
      battery: "3060 mAh",
      operatingSystem: "Android v5.0 (Lollipop)",
      ram: "2GB"
  },
  {
    id: 7,
    title: "OnePlus 9 Pro",
    price: 969.0,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmlMtRhl1opnnFWwf_m8RQPhA0OHvrCzW47EuDCcvq2A&s",
    quantity: 1,
    internalMemory: "32GB",
      display: "5.2 inches",
      processor: "Qualcomm Snapdragon 625",
      rearCamera: "12 MP",
      frontCamera: "5 MP",
      battery: "3000 mAh",
      operatingSystem: "Android v7.0 (Nougat)",
      ram: "2GB"
  },
  {
    id: 8,
    title: "Sony Xperia 1 II",
    price: 1200.0,
    img: "https://cdn.mos.cms.futurecdn.net/yemimRERtG5AAfYzeCWSjH.jpg",
    quantity: 1,
    display: "5.1 inches",
    processor: "Qualcomm Snapdragon 820",
    rearCamera: "12 MP",
    frontCamera: "5 MP",
    battery: "3000 mAh",
    operatingSystem: "Android v6.0 (Marshmallow)",
    ram: "4GB"
  },
  {
    id: 9,
    title: "Huawei P40 Pro",
    price: 900.0,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOCcMXbgDBaXBnTDk1Lb7hPuw5MSCZC0iMhg&s",
    quantity: 1,
    internalMemory: "16GB",
      display: "5.5 inches",
      processor: "Mediatek MT6795 Helio X10",
      rearCamera: "13 MP",
      frontCamera: "5 MP",
      battery: "3060 mAh",
      operatingSystem: "Android v5.0 (Lollipop)",
      ram: "2GB"
  },
  {
    id: 10,
    title: "Oppo Find X3 Pro",
    price: 1149.0,
    img: "https://images.hindustantimes.com/tech/htmobile4/P35499/images/Design/141643-v2-oppo-find-x3-pro-mobile-phone-large-3.jpg",
    quantity: 1,
    internalMemory: "128GB",
      display: "6.7 inches Foldable Dynamic AMOLED",
      processor: "Qualcomm Snapdragon 888",
      rearCamera: "12 MP + 12 MP",
      frontCamera: "10 MP",
      battery: "3300 mAh",
      operatingSystem: "Android v11",
      ram: "8GB"
  },
  {
    id: 11,
    title: "Samsung Galaxy Note 20",
    price: 999.0,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVOEjCKZZPh1hWHOzxREpWqiaseZY9riM96A&s",
    quantity: 1,
    internalMemory: "32GB",
      display: "5.2 inches",
      processor: "Qualcomm Snapdragon 625",
      rearCamera: "12 MP",
      frontCamera: "5 MP",
      battery: "3000 mAh",
      operatingSystem: "Android v7.0 (Nougat)",
      ram: "2GB"
  },
  {
    id: 12,
    title: "LG V60 ThinQ",
    price: 799.0,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-ff_V-FWOXDNJi_xvfsTF-3ziobVI0zvF7w&s",
    quantity: 1,
    internalMemory: "16GB",
      display: "5.5 inches",
      processor: "Mediatek MT6795 Helio X10",
      rearCamera: "13 MP",
      frontCamera: "5 MP",
      battery: "3060 mAh",
      operatingSystem: "Android v5.0 (Lollipop)",
      ram: "2GB"
  },
  {
    id: 13,
    title: "Motorola Razr 5G",
    price: 1399.0,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFFBrWKRd7ZWJ2PA_R7B02rlhOxBY07YSPkw&s",
    quantity: 1,
    display: "5.1 inches",
    processor: "Qualcomm Snapdragon 820",
    rearCamera: "12 MP",
    frontCamera: "5 MP",
    battery: "3000 mAh",
    operatingSystem: "Android v6.0 (Marshmallow)",
    ram: "4GB"
  },
  {
    id: 14,
    title: "ZTE Axon 30 Ultra",
    price: 749.0,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTfArbMqjjLYUN_13HcattjcIYqC1doDBdhQ&s",
    quantity: 1,
    internalMemory: "16GB",
      display: "5.5 inches",
      processor: "Mediatek MT6795 Helio X10",
      rearCamera: "13 MP",
      frontCamera: "5 MP",
      battery: "3060 mAh",
      operatingSystem: "Android v5.0 (Lollipop)",
      ram: "2GB"
  },
  {
    id: 15,
    title: "Xiaomi Mi 11 Ultra",
    price: 1299.0,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUmDmVYCJyRbL76PKwJQWMTpUCAIB96zTcEg&s",
    quantity: 1,
    internalMemory: "128GB",
      display: "6.7 inches Foldable Dynamic AMOLED",
      processor: "Qualcomm Snapdragon 888",
      rearCamera: "12 MP + 12 MP",
      frontCamera: "10 MP",
      battery: "3300 mAh",
      operatingSystem: "Android v11",
      ram: "8GB"
  },
  {
    id: 16,
    title: "Apple iPhone SE (2020)",
    price: 399.0,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2or3qmwEcS4TtgHtGotoCFQfNed8doLmf2w&s",
    quantity: 1,
    display: "5.1 inches",
    processor: "Qualcomm Snapdragon 820",
    rearCamera: "12 MP",
    frontCamera: "5 MP",
    battery: "3000 mAh",
    operatingSystem: "Android v6.0 (Marshmallow)",
    ram: "4GB"
  },
  {
      id: 17,
      title: "Samsung Galaxy Z Flip 3",
      price: 999.0,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw9tKGBqIQ0lzBa-W3oBcgnsnGM6uNG3O2Pw&s",
      quantity: 1,
      internalMemory: "128GB",
      display: "6.7 inches Foldable Dynamic AMOLED",
      processor: "Qualcomm Snapdragon 888",
      rearCamera: "12 MP + 12 MP",
      frontCamera: "10 MP",
      battery: "3300 mAh",
      operatingSystem: "Android v11",
      ram: "8GB"
  },
  {
    id: 18,
    title: "Google Pixel 5",
    price: 699.0,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRF_Alh2ztEF_ELReLo9B8N3nYgogaxlVG5JA&s",
    quantity: 1,
    internalMemory: "128GB",
    display: "6.0 inches OLED",
    processor: "Qualcomm Snapdragon 765G",
    rearCamera: "12.2 MP + 16 MP",
    frontCamera: "8 MP",
    battery: "4080 mAh",
    operatingSystem: "Android v11",
    ram: "8GB"
},
{
    id: 19,
    title: "OnePlus 8T",
    price: 749.0,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCvhNRfWCXnGxaSeXSwFrgP6TqTrsW4qhYeg&s",
    quantity: 1,
    internalMemory: "256GB",
    display: "6.55 inches Fluid AMOLED",
    processor: "Qualcomm Snapdragon 865",
    rearCamera: "48 MP + 16 MP + 5 MP + 2 MP",
    frontCamera: "16 MP",
    battery: "4500 mAh",
    operatingSystem: "Android v11",
    ram: "12GB"
}

];
